### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by vsudeikin** [awd-studio/nova-poshta#5]
## Problem/Motivation

> (Why the issue was filed)

## Expected behaviour

> (What you expected to happen)

## Actual behaviour

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix, describe the rationale behind it)

**Comment by vsudeikin** [comment]
Online searching methods:

<?php

use NovaPoshta\Settings\Settings;
use NovaPoshta\Models\Address;

$key      = 'myAuthKeyHash';
$settings = Settings::getInstance()->auth($key);

$address  = new Address($settings);

// Just start typing, no needed save values to database!

$options = [
    'CityName' => 'К',
    //'CityName' => 'Ки',
    //'CityName' => 'Киї',
];
$response = $model->searchSettlements($options); // Get towns list

$options = [
    'StreetName'    => 'Шев',
    'SettlementRef' => 'e715719e-4b33-11e4-ab6d-005056801329',
    'Limit'         => 10,
];
$response = $address->searchSettlements($options); //

**Comment by awd-studio** [comment]
@vsudeikin, приветствую! 

Благодарю за ISSUE, описание исправлено. 

Данная библиотека, хоть еще и находится в глубокой альфе, но, в текущей реализации, развиваться уже не будет. 

Так часто бывает - не дожив до релиза 1.0 библиотека полностью рефакторится и выпускается в новом ключе, с условной версией 2.0 :) 

Максимум, могу пообещать вносить небольшие фиксы, если в них будет острая необходимость. 
Но удалять - не собираюсь 100%.

Если интересно - вот страничка обновленного проекта: https://github.com/awd-studio/NovaPoshta
Там сделан упор на простоту использования и стабильность работы.

**Comment by vsudeikin** [comment]
Круто! Я просмотрел реализации NP, и мне понравились ваши.

**Comment by awd-studio** [comment]
Спасибо за оценку!
